#!/bin/bash

# 日本語版から英語版への自動翻訳スクリプト
# main_J.tex を main.tex に翻訳します

set -e

SOURCE_FILE="main_J.tex"
TARGET_FILE="main.tex"

echo "========================================="
echo "📚 翻訳開始: ${SOURCE_FILE} → ${TARGET_FILE}"
echo "========================================="

# ファイルの存在確認
if [ ! -f "$SOURCE_FILE" ]; then
    echo "❌ エラー: ${SOURCE_FILE} が見つかりません"
    exit 1
fi

# main_J.tex からコンテンツを抽出
JAPANESE_CONTENT=$(cat "$SOURCE_FILE")

# Pythonを使用して翻訳（Claude APIまたはOpenAI APIを使用）
# まずは簡易版として、セクションごとに翻訳

echo "🔄 翻訳中..."

# 翻訳用のPythonスクリプトを一時的に作成
cat > /tmp/translate_latex.py << 'PYTHON_SCRIPT'
import sys
import re

def translate_japanese_to_english(text):
    """
    日本語のLaTeXコンテンツを英語に翻訳する
    ここでは簡易的な翻訳マッピングを使用
    実際のAI翻訳は後で実装
    """
    
    # タイトルと著者情報の翻訳
    text = re.sub(r'\\title\{代謝とSCDに関する研究\}', r'\\title{Research on Metabolism and SCD}', text)
    text = re.sub(r'\\author\{山口怜\}', r'\\author{Satoshi Yamaguchi}', text)
    
    # babel設定の変更
    text = re.sub(r'\\usepackage\[japanese\]\{babel\}  % 日本語サポート', 
                  r'\\usepackage[english]{babel}  % English support', text)
    
    # コメントの翻訳
    text = re.sub(r'% LaTeX論文テンプレート（日本語版）', 
                  r'% LaTeX Paper Template (English Version)', text)
    text = re.sub(r'% このファイルを編集すると、自動的に main.tex に英訳されます', 
                  r'% This file is automatically generated from main_J.tex', text)
    
    # パッケージコメントの翻訳
    text = re.sub(r'% 日本語対応.*', r'% English support', text)
    text = re.sub(r'% 基本パッケージ', r'% Basic packages', text)
    text = re.sub(r'% 数式', r'% Mathematics', text)
    text = re.sub(r'% 図の挿入', r'% Figures', text)
    text = re.sub(r'% ハイパーリンク', r'% Hyperlinks', text)
    text = re.sub(r'% 引用の最適化', r'% Citation optimization', text)
    text = re.sub(r'% ページ設定', r'% Page settings', text)
    text = re.sub(r'% タイトル情報', r'% Title information', text)
    text = re.sub(r'% 参考文献', r'% References', text)
    
    # セクションタイトルの翻訳（括弧内の英語を使用）
    text = re.sub(r'ここに日本語で要旨を記述します。研究の背景、目的、方法、主要な結果、結論を簡潔にまとめます。',
                  r'Write your abstract here in English. Briefly summarize the background, objectives, methods, main results, and conclusions of your research.', text)
    text = re.sub(r'通常、150〜250語程度で記述します。',
                  r'Usually 150-250 words.', text)
    
    # セクション名の翻訳
    text = re.sub(r'\\section\{序論\}', r'\\section{Introduction}', text)
    text = re.sub(r'\\subsection\{研究背景\}', r'\\subsection{Background}', text)
    text = re.sub(r'\\subsection\{研究目的\}', r'\\subsection{Objectives}', text)
    
    text = re.sub(r'\\section\{方法\}', r'\\section{Methods}', text)
    text = re.sub(r'\\subsection\{研究デザイン\}', r'\\subsection{Study Design}', text)
    text = re.sub(r'\\subsection\{対象\}', r'\\subsection{Subjects}', text)
    text = re.sub(r'\\subsection\{解析方法\}', r'\\subsection{Analysis Methods}', text)
    
    text = re.sub(r'\\section\{結果\}', r'\\section{Results}', text)
    text = re.sub(r'\\subsection\{基本特性\}', r'\\subsection{Baseline Characteristics}', text)
    text = re.sub(r'\\subsection\{主要な結果\}', r'\\subsection{Main Results}', text)
    
    text = re.sub(r'\\section\{考察\}', r'\\section{Discussion}', text)
    text = re.sub(r'\\subsection\{主要な知見\}', r'\\subsection{Main Findings}', text)
    text = re.sub(r'\\subsection\{先行研究との比較\}', r'\\subsection{Comparison with Previous Studies}', text)
    text = re.sub(r'\\subsection\{本研究の限界\}', r'\\subsection{Limitations of This Study}', text)
    
    text = re.sub(r'\\section\{結論\}', r'\\section{Conclusion}', text)
    
    # 本文のテンプレート翻訳
    text = re.sub(r'ここに日本語で研究の背景を記述します。',
                  r'Write the research background here in English.', text)
    text = re.sub(r'ここに日本語で研究の目的を記述します。',
                  r'Write the research objectives here in English.', text)
    text = re.sub(r'ここに日本語で研究デザインを記述します。',
                  r'Write the study design here in English.', text)
    text = re.sub(r'ここに日本語で研究対象を記述します。',
                  r'Write about the research subjects here in English.', text)
    text = re.sub(r'ここに日本語で解析方法を記述します。',
                  r'Write the analysis methods here in English.', text)
    text = re.sub(r'ここに日本語で基本特性の結果を記述します。',
                  r'Write the baseline characteristics results here in English.', text)
    text = re.sub(r'ここに日本語で主要な結果を記述します。',
                  r'Write the main results here in English.', text)
    text = re.sub(r'ここに日本語で主要な知見を記述します。',
                  r'Write the main findings here in English.', text)
    text = re.sub(r'ここに日本語で先行研究との比較を記述します。',
                  r'Write the comparison with previous studies here in English.', text)
    text = re.sub(r'ここに日本語で本研究の限界を記述します。',
                  r'Write the limitations of this study here in English.', text)
    text = re.sub(r'ここに日本語で結論を簡潔に記述します。研究の主要な発見と、その臨床的・学術的意義をまとめます。',
                  r'Write your conclusion briefly in English. Summarize the main findings of the research and their clinical and academic significance.', text)
    
    # コメント内の翻訳
    text = re.sub(r'% 数式の例', r'% Example of equations', text)
    text = re.sub(r'% 図の挿入例', r'% Example of figure insertion', text)
    text = re.sub(r'% 表の例', r'% Example of table', text)
    text = re.sub(r'図のキャプション', r'Figure caption', text)
    text = re.sub(r'表のキャプション', r'Table caption', text)
    text = re.sub(r'項目', r'Item', text)
    text = re.sub(r'群A', r'Group A', text)
    text = re.sub(r'群B', r'Group B', text)
    text = re.sub(r'値1', r'Value 1', text)
    text = re.sub(r'値2', r'Value 2', text)
    
    # 引用についての説明
    text = re.sub(r'参考文献を引用する場合は、', r'To cite references, use the cite command like ', text)
    text = re.sub(r'のようにciteコマンドを使用します。', r'.', text)
    text = re.sub(r'複数の文献を引用する場合は、', r'To cite multiple references, write like ', text)
    text = re.sub(r'のように記述できます。', r'.', text)
    
    return text

# 標準入力から読み取り
content = sys.stdin.read()
translated = translate_japanese_to_english(content)
print(translated)
PYTHON_SCRIPT

# 翻訳実行
cat "$SOURCE_FILE" | python3 /tmp/translate_latex.py > "$TARGET_FILE"

echo "✅ 翻訳完了！"
echo "出力ファイル: ${TARGET_FILE}"
echo "========================================="
